### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Kazachenko1998/Johniac#1]
1. Избавьтесь от нестандартных заголовочных файлов `mem.h` и `conio.h`. Первый можно просто заменить на стандартный `string.h`, со вторым возможно чуть посложнее.
2. Нет автоматической сборки с помощью `make`. Это обязательное требование.
3. Нигде не освобождаете выделенную через `malloc` память.
4. `fgets` позволяет читать и из консоли.
5. `double` всё ещё некорректное представление для чисел Johniac'а.
6. Ваш файл с константами всё ещё не является структурой.
7. `func_Sp_` и `func_Sp_` всё же должны быть операциями с половиной регистра, а не с 12 соседними регистрами.
8. Хотелось бы примеры программ, на которых вы испытывали ваш симулятор.

**Comment by Kazachenko1998** [comment]
1 - исправил, но теперь клавиши ENTER и др нельзя использовать, поэтому обычная клавиатура
3 - а memset разве этого не делает? это проделывается для всех массивов вроде...
4 - аналогично пункту 1 
5 - исправил
7 - исправил

**Comment by Kazachenko1998** [comment]
2 - создал MakeFile(а почему нельзя использовать тот которые генерирует CLine?)
8 - написал простой пример которые демонстрирует работу некоторых функций. 
3 - Не очень понимаю зачем переменные выносить в отдельную структуру? Мы же просто к ним обращаемся и изменяем, у них нет методов и это простые типы.

**Comment by gagarski** [comment]
> 2 - создал MakeFile(а почему нельзя использовать тот которые генерирует CLine?)
CLion использует CMake. Он, конечно, в свою очередь генерирует Makefile, но одним из требований было написание Makefile руками. Можете сравнить, что получается

> 3 - а memset разве этого не делает? это проделывается для всех массивов вроде...

Нет. Почитайте документацию про `memset` и `free`.

1. gets всё ещё есть
2. Пройдитесь по предупреждениям компилятора
3. https://github.com/Kazachenko1998/Johniac/blob/75d8b7e2c1ab658c519f084c8400efa58bbe78f5/help_func.c#L59-L60
Выглядит, как бред. Посмотрите на результат `sizeof` в данном случае, эти строки явно делают не то, что вы хотите.
4. Фиксированные имена файлов мне не очень нравятся, лучше бы сделать задаваемыми из аргументов командной строки (но это с самым низким приоритетом)

По отчёту:

1. Вместо фразы "(раскрывается структура основной части)" следует раскрыть структуру основной части (согласно оглавлению)
2. Замените исходники ссылкой на репозиторий, этого будет достаточно, сэкономьте бумагу.
3. Слово "функционал" в заключении замените

**Comment by Kazachenko1998** [comment]
исправил остальные замечания.
